name: CI (main)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  audit:
    uses: ./.github/workflows/audit.yml
  build:
    needs: audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy backend
        env:
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
        run: curl -v $DEPLOY_URL
